api/urls.py
from django.urls import path

from .views import (
    FavoriteView, GetIngredientsView, PurchasesView, SubscribeView
)


urlpatterns = [
    path('favorites', FavoriteView.as_view(), name='add_favorite'),
    path(
        'favorites/<int:recipe_id>', FavoriteView.as_view(),
        name='remove_favorite'
    ),
    path('ingredients/', GetIngredientsView.as_view(), name='get_ingredients'),
    path('purchases', PurchasesView.as_view(), name='purchases'),
    path(
        'purchases/<int:recipe_id>', PurchasesView.as_view(),
        name='remove_purchases'
    ),
    path('subscriptions', SubscribeView.as_view(),
         name='add_subscription'),
    path(
        'subscriptions/<int:author_id>', SubscribeView.as_view(),
        name='remove_subscription'
    ),
]

foodgram/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    # register and auth
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/author/', TemplateView.as_view(
        template_name='about.html'
    ), name='about_author'),
    path('about/tech/', TemplateView.as_view(
        template_name='about.html'
    ), name='about_tech'),
    path('api/', include('api.urls')),
    path('', include("recipes.urls")),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)

recipes/urls.py
from django.urls import path

from .views import (
    AuthorRecipeListView, FavoriteListView, MyFollowListView,
    RecipeCreateFormView, RecipeEditFormView, RecipeDetailView,
    RecipeDelete, RecipeIndexListView, ShopingList, shoplist_download
)


urlpatterns = [
    path('author/<pk>/', AuthorRecipeListView.as_view(), name='author'),
    path('new', RecipeCreateFormView.as_view(), name='newrecipe'),
    path('favorites/', FavoriteListView.as_view(), name='favorites'),
    path('recipe/<int:pk>/', RecipeDetailView.as_view(), name='recipe'),
    path(
        'recipe/<int:pk>/edit/', RecipeEditFormView.as_view(),
        name='edit_recipe'
    ),
    path(
        'recipe/<int:pk>/delete/', RecipeDelete.as_view(),
        name='delete_recipe'
    ),
    path(
        'mysubscriptions', MyFollowListView.as_view(),
        name='mysubscriptions'
    ),
    path('shoplist', ShopingList.as_view(), name='shoplist'),
    path('shoplist/download/', shoplist_download, name='shoplist_download'),
    path('', RecipeIndexListView.as_view(), name='index'),
]

recipes/models.py
from django.db import models

from users.models import User


class Ingredient(models.Model):
    name = models.CharField(max_length=100)
    unit = models.CharField(max_length=15)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=15)
    slug = models.SlugField()
    checkbox_style = models.CharField(max_length=15)

    def __str__(self):
        return self.name


class Recipe(models.Model):

    class Meta:
        ordering = ['-pub_date']

    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='recipes'
    )
    name = models.CharField(max_length=100)
    pub_date = models.DateTimeField("Дата добавления", auto_now_add=True)
    image = models.ImageField(upload_to='recipes/')
    description = models.TextField(max_length=1200)
    ingredients = models.ManyToManyField(
        Ingredient, through='Amount', through_fields=('recipe', 'ingredient')
    )
    tag = models.ManyToManyField(Tag, related_name='tag')
    prep_time = models.IntegerField()

    def __str__(self):
        return self.name


class Amount(models.Model):
    units = models.IntegerField()
    ingredient = models.ForeignKey(
        Ingredient, on_delete=models.CASCADE, related_name='ingredient'
    )
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)


class ShopList(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='buyer'
    )
    recipe = models.ForeignKey(
        Recipe, on_delete=models.CASCADE, related_name='recipe_to_shop'
    )

recipes/forms.py
from django import forms
from django.forms.widgets import CheckboxSelectMultiple

from .models import Tag, Recipe


class TagsFilter(forms.Form):

    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=CheckboxSelectMultiple(),
        to_field_name='slug'
    )


class RecipeForm(forms.ModelForm):

    class Meta:
        model = Recipe
        fields = (
            'name', 'image', 'description', 'tag', 'prep_time'
        )
        widgets = {'tag': forms.CheckboxSelectMultiple(), }

recipes/views.py
import csv

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import F, Sum
from django.http import Http404, HttpResponse
from django.views.generic import (
    CreateView, ListView, DetailView, UpdateView, DeleteView
)
from django.shortcuts import get_object_or_404, redirect, reverse

from .extras import create_ingredients_amounts, get_all_tags, get_filters
from .forms import RecipeForm
from .models import Recipe, ShopList, User


class RecipeIndexListView(ListView):

    model = Recipe
    template_name = 'index.html'
    paginate_by = 6

    def get_queryset(self):
        qs = super().get_queryset()

        return get_filters(self.request, qs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({'all_tags': get_all_tags()})

        return context


class RecipeDetailView(DetailView):

    model = Recipe
    template_name = 'recipe.html'


class AuthorRecipeListView(RecipeIndexListView):

    template_name = 'author.html'

    def get_queryset(self):
        current_user = get_object_or_404(User, pk=self.kwargs.get('pk'))
        qs = Recipe.objects.filter(author=current_user)

        return get_filters(self.request, qs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        author = get_object_or_404(User, pk=self.kwargs.get('pk'))
        context['author'] = author

        return context


class FavoriteListView(LoginRequiredMixin, RecipeIndexListView):

    template_name = 'favorite.html'

    def get_queryset(self):
        author = self.request.user
        qs = Recipe.objects.filter(favrecipe__user=author).all()

        return get_filters(self.request, qs)


class MyFollowListView(LoginRequiredMixin, ListView):

    model = Recipe
    template_name = 'mysubscriptions.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_user = self.request.user
        authors = User.objects.filter(following__user=current_user)
        context['authors'] = authors
        fav_recipes = {}
        for author in authors:
            fav_recipes[author] = Recipe.objects.filter(
                author=author
            ).order_by('-pub_date')[:3]
        context['fav_recipes'] = fav_recipes

        return context


class RecipeCreateFormView(LoginRequiredMixin, CreateView):

    form_class = RecipeForm
    template_name = 'formrecipe.html'
    success_url = 'index'

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.author = self.request.user
        form_data = form.data
        ingredients = [
            key for key in form_data if key.startswith('nameIngredient_')
        ]
        if not ingredients:
            form.add_error(
                'description',
                'Необходимо указать хотя бы один ингредиент для рецепта'
            )
            return self.form_invalid(form)
        instance.save()
        create_ingredients_amounts(instance, form_data)
        form.save_m2m()

        return redirect(self.success_url)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({'all_tags': get_all_tags()})

        return context


class RecipeEditFormView(LoginRequiredMixin, UpdateView):

    form_class = RecipeForm
    model = Recipe
    template_name = 'formrecipe.html'

    def form_valid(self, form):
        instance = form.save(commit=False)
        form_data = form.data
        instance.amount_set.all().delete()
        ingredients = [
            key for key in form_data if key.startswith('nameIngredient_')
        ]
        if not ingredients:
            form.add_error(
                'description',
                'Необходимо указать хотя бы один ингредиент для рецепта'
            )
            return self.form_invalid(form)
        instance.save()
        create_ingredients_amounts(instance, form_data)
        form.save_m2m()
        return redirect(self.get_success_url())

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.author != self.request.user:
            raise Http404('Вы не являетесь автором данного рецепта')

        return super(RecipeEditFormView, self).dispatch(
            request, *args, **kwargs
        )

    def get_success_url(self):
        return reverse('recipe', kwargs={'pk': self.object.id})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({'all_tags': get_all_tags()})
        context.update({'is_edit': True})

        return context


class RecipeDelete(LoginRequiredMixin, DeleteView):

    model = Recipe
    success_url = 'index'

    def get(self, *args, **kwargs):
        return self.post(*args, **kwargs)

    def get_object(self, queryset=None):
        instance = super(RecipeDelete, self).get_object()
        if instance.author != self.request.user:
            raise Http404('Вы не являетесь автором данного рецепта')

        return instance


class ShopingList(ListView):

    model = ShopList
    template_name = 'shoplist.html'


def shoplist_download(request):
    recipes = Recipe.objects.filter(recipe_to_shop__user=request.user)
    ingredients = recipes.annotate(
        title=F('amount__ingredient__name'),
        units=F('amount__ingredient__unit')
    ).values('title', 'units').order_by('title').annotate(
        total=Sum('amount__units')
    )
    response = HttpResponse(content_type='text/text')
    response['Content-Disposition'] = 'attachment; filename="shoplist.txt"'

    writer = csv.writer(response)
    writer.writerow([f'Список покупок: {request.user.get_full_name()}'])
    writer.writerow([])
    writer.writerow(['Блюда:'])
    for recipe in recipes:
        writer.writerow([recipe.name])
    writer.writerow([])
    writer.writerow(['Ингредиенты:'])
    for ingredient in ingredients:
        if ingredient['title']:
            name = ingredient['title']
            dimension = ingredient['units']
            total = ingredient['total']
            writer.writerow([f'{name} - {total} {dimension}'])

    return response

templates/about.html
{% extends 'base.html' %}
{% block title %}Обаут{% endblock %}
{% block content %}
{% load static %}
{% include 'nav.html' %}
<link rel="stylesheet" href="{% static 'pages/single.css' %}">
  <div class="single-card" data-id="{{ recipe.id }}">
    <div class="single-card__info">
      <div class="single-card__header-info">
        <h1 class="single-card__title">{{ headline }}</h1>
      </div>
      <div class="single-card__section">
           <img src="{% static 'about.png' %}" alt="">
      </div>
    </div>
  </div>
{% endblock %}

templates/author.html
{% extends 'base.html' %}
{% block title %}{{ author.get_full_name }}{% endblock %}
{% block content %}
{% load static recipes_extras %}
{% include 'nav.html' with index=True %}
{% csrf_token %}
<link rel="stylesheet" href="{% static 'pages/index.css' %}">
  <div class="main__header">
    <h1 class="main__title">{{ author.get_full_name }}</h1>
      {% include 'tags_filter.html' %}
  </div>
  {% if request.user.is_authenticated %}
  {% if request.user != author %}
    <div class="author-subscribe" data-author="{{ author.id }}">
    {% if author|is_following:request.user %}
      <p style="padding: 0 0 2em 0;">
        <button class="button button_style_light-blue button_size_auto" name="subscribe" >Отписаться от автора</button></p>
    {% else %}
      <p style="padding: 0 0 2em 0;">
        <button class="button button_style_light-blue button_size_auto" name="subscribe" data-out>Подписаться на автора</button></p>
    {% endif %}
    </div>
  {% endif %}
  {% endif %}
  <div class="card-list">
  {% for recipe in object_list %}
    <div class="card" data-id={{ recipe.id }}>
      <a href="{% url 'recipe' recipe.pk %}" class="link" target="_self"><img src="{{ recipe.image.url }}" alt="Какой-то текст" class="card__image"></a>
        <div class="card__body">
          <a class="card__title link" href="{% url 'recipe' recipe.pk %}" target="_self">{{ recipe.name }}</a>
            <ul class="card__items">
            {% include 'tags.html' %}
            </ul>
            <div class="card__items card__items_column">
              <p class="card__text"><span class="icon-time"></span>{{ recipe.prep_time }} мин.</p>
               <p class="card__text"><span class="icon-user"></span> <a
                            href="{% url 'author' author.id %}" style="color: black">{{ recipe.author.get_full_name }}</a></p>
            </div>

        {% if request.user.is_authenticated %}
          <div class="card__footer">
            <button class="button button_style_light-blue" name="purchases" data-out><span class="icon-plus button__icon"></span>Добавить в покупки</button>
            {% if recipe|is_favorite:user %}
            <button class="button button_style_none" name="favorites" ><span class="icon-favorite icon-favorite_active"></span></button>
                  <div class="single-card__favorite-tooltip tooltip"></div>
            {% else %}
            <button class="button button_style_none" name="favorites" data-out><span class="icon-favorite icon-favorite"></span></button>
                  <div class="single-card__favorite-tooltip tooltip"></div>
            {% endif %}
          </div>
        {% endif %}
        </div>
    </div>
  {% endfor %}
  </div>
    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static 'js/components/MainCards.js' %}"></script>
    <script src="{% static 'js/components/Purchases.js' %}"></script>
    <script src="{% static 'js/components/Favorites.js' %}"></script>
    <script src="{% static 'js/components/Subscribe.js' %}"></script>

    <script src="{% static 'js/components/AuthorRecipe.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>
    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'authorRecipe.js' %}"></script>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{% block title %}{% endblock %} | Foodgram</title>
<!-- Load static -->
{% load static %}
</head>
<body>
  <main class="main container">
  {% block content %}
  <!-- содержимое страницы -->
  {% endblock content %}
  </main>
  {% include 'footer.html' %}
</body>
</html>

templates/favorite.html
{% extends 'base.html' %}
{% block title %}Избранное{% endblock %}
{% block content %}
{% load static user_filters recipes_extras %}
{% csrf_token %}
{% include 'nav.html' with favorites=True %}
<link rel="stylesheet" href="{% static 'pages/index.css' %}">
  <div class="main__header">
    <h1 class="main__title">Избранное</h1>
      {% include 'tags_filter.html' %}
  </div>
    <div class="card-list">
        {% for recipe in object_list %}
        <div class="card" data-id={{ recipe.id }}>
            <a href="{% url 'recipe' recipe.pk %}" class="link" target="_self"><img src="{{ recipe.image.url }}" alt="Какой-то текст" class="card__image"></a>
            <div class="card__body">
                <a class="card__title link" href="{% url 'recipe' recipe.pk %}" target="_self">{{ recipe.name }}</a>
                <ul class="card__items">
                    {% include 'tags.html' %}
                </ul>
                <div class="card__items card__items_column">
                    <p class="card__text"><span class="icon-time"></span>{{ recipe.prep_time }} мин.</p>
                    <p class="card__text"><span class="icon-user"></span> <a
                            href="{% url 'author' recipe.author.id %}" style="color: black">{{ recipe.author.get_full_name }}</a></p>
                </div>
            </div>
            <div class="card__footer">
                <button class="button button_style_light-blue" name="purchases" data-out><span
                        class="icon-plus button__icon"></span>Добавить в покупки</button>
                {% if recipe|is_favorite:user %}
                        <button class="button button_style_none" name="favorites" onclick="location.reload()"><span
                                class="icon-favorite icon-favorite_big icon-favorite_active"></span></button>
                        <div class="single-card__favorite-tooltip tooltip"></div>
                 {% else %}
                        <button class="button button_style_none" name="favorites" data-out><span class="icon-favorite icon-favorite_big"></span></button>
                        <div class="single-card__favorite-tooltip tooltip"></div>
                 {% endif %}
            </div>
        </div>
        {% endfor %}
    </div>
  {% include 'paginator.html' %}
  <script src="{% static 'js/components/MainCards.js' %}"></script>
  <script src="{% static 'js/components/Purchases.js' %}"></script>
  <script src="{% static 'js/components/Favorites.js' %}"></script>
  <script src="{% static 'js/config/config.js' %}"></script>
  <script src="{% static 'js/components/CardList.js' %}"></script>
  <script src="{% static 'js/components/Header.js' %}"></script>
  <script src="{% static 'js/api/Api.js' %}"></script>
  <script src="{% static 'favorite.js' %}"></script>
{% endblock %}

templates/footer.html
<footer class="footer">
  <div class="footer__container container">
    <a href="#" class="footer__brand link">Продуктовый помощник</a>
      <ul class="footer__items">
        <li class="footer__item"><a href="{% url 'about_author' %}" class="footer__link link">Об авторе </a></li>
        <li class="footer__item"><a href="{% url 'about_tech' %}" class="footer__link link">Технологии</a></li>
      </ul>
  </div>
</footer>

templates/formrecipe.html
{% extends 'base.html' %}
{% block title %}Создание рецепта{% endblock %}
{% block content %}
    {% load static recipes_extras %}
    {% include 'nav.html' with recipeform=True %}
    <link rel="stylesheet" href="{% static 'pages/form.css' %}">
    <div class="main__header">
        <h1 class="main__title">Создание рецепта</h1>
    </div>
        <div class="form-container">
        <form class="form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form__group">
                <label for={{ form.name.id_for_label }} class="form__label">Название рецепта</label>
                <div class="form__field-group">
                    <input type="text" id="id_name" name="{{ form.name.name }}" class="form__input"
                    {% if is_edit %} value="{{ form.name.value }}"{% endif %}>
                    {% if form.errors %}
                    <span class="form__error">{{ form.name.errors }}</span>
                    {% endif %}
                </div>
            </div>
            <div class="form__group">
                <p class="form__label">Теги</p>
                <div class="form__field-group">
                    <div class="tags">
                        {% for tag_choice, tag_value in form.tag.field.choices %}
                            <div class="tags__item">
                                <input type="checkbox" name="tag" value="{{ tag_choice.instance.pk }}" id="id_{{ tag_choice.instance.slug }}" class="tags__checkbox tags__checkbox_style_{{ tag_choice.instance.checkbox_style }}">
                                <label for="id_{{ tag_choice.instance.slug }}" class="tags__label">{{ tag_choice.instance.name }}</label>
                            </div>
                        {% endfor %}
                    </div>
                    {% if form.errors %}
                    <span class="form__error">{{ form.tag.errors }}</span>
                    {% endif %}
                </div>
            </div>
            <div class="form__group">
                <label for="nameIngredient" class="form__label">Ингредиенты</label>
                <div class="form__field-group">
                    <div class="form__field-group-ingredientes">
                        <div class="form__dropdown">
                            <input type="text" id="nameIngredient" class="form__input">
                            <div class="form__dropdown-items"></div>
                        </div>
                        <input type="number" id="cantidad" class="form__input" min="0">
                        <label for="cantidad" class="form__label" id="cantidadVal">шт.</label>
                    </div>
                    <div class="form__field-group-ingredientes-container">
                    </div>
                    <span class="form__ingredient-link" id="addIng">Добавить ингредиент</span>
                </div>
            </div>
            <div class="form__group">
                <label for="id_time" class="form__label">Время приготовления</label>
                <div class="form__field-group form__field-group_time">
                    <input type="text" id="id_time" name="{{ form.prep_time.name }}" class="form__input"
                         {% if form.name.value %} value="{{ form.prep_time.value }}" {% endif %}>
                    <label for="id_time" class="form__label">минут</label>
                    {% if form.errors %}
                    <span class="form__error">{{ form.prep_time.errors }}</span>
                    {% endif %}
                </div>
            </div>
            <div class="form__group">
                <label for="id_description" class="form__label">Описание</label>
                <div class="form__field-group">
                    <textarea name="{{ form.description.name }}" id="id_description" rows="8" class="form__textarea"
                    >{% if is_edit %} {{ form.description.value }} {% endif %}</textarea>
                    {% if form.errors %}
                    <span class="form__error">{{ form.description.errors }}</span>
                    {% endif %}
                </div>
            </div>
            <div class="form__group">
                <span class="form__label">Загрузить фото</span>
                <div class="form__field-group">
                    <label for="id_file" class="form__file-button">Выбрать файл</label>
                    <input type="file" class="form__file" name="image"
                           id="id_file" {% if is_edit %} value="{{ recipe.image }}"{% endif %}>
                    {% if form.errors %}
                    <span class="form__error">{{ form.image.errors }}</span>
                    {% endif %}
                </div>
            </div>
            <div class="form__footer">
            {% if is_edit %}
                <button class="button button_style_blue">Изменить рецепт</button>
                <a style="margin-left: 2.5em" href="{% url 'delete_recipe' recipe.id %}" class="form__ingredient-link">Удалить</a>
            {% else %}
                <button class="button button_style_blue">Создать рецепт</button>
            {% endif %}
            </div>
        </form>
    </div>
    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>
    <script src="{% static 'js/utils/debouncing.js' %}"></script>
    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'formRecipe.js' %}"></script>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block title %}Рецепты{% endblock %}
{% block content %}
  {% load static recipes_extras user_filters %}
  {% include 'nav.html' with index=True %}
  <link rel="stylesheet" href="{% static 'pages/index.css' %}">
  <div class="main__header">
    <h1 class="main__title">Рецепты</h1>
      {% include 'tags_filter.html' %}
  </div>
    <div class="card-list">
        {% for recipe in object_list %}
        <div class="card" data-id={{ recipe.id }}>
            <a href="{% url 'recipe' recipe.id %}" class="link" target="_self"><img src="{{ recipe.image.url }}" alt="Какой-то текст" class="card__image"></a>
            <div class="card__body">
                <a class="card__title link" href="{% url 'recipe' recipe.id %}" target="_self">{{ recipe.name }}</a>
                <ul class="card__items">
                    {% include 'tags.html' %}
                </ul>
                <div class="card__items card__items_column">
                    <p class="card__text"><span class="icon-time"></span>{{ recipe.prep_time }} мин.</p>
                    <p class="card__text"><span class="icon-user"></span> <a
                            href="{% url 'author' recipe.author.id %}" style="color: black">{{ recipe.author.get_full_name }}</a></p>
                </div>
            </div>
            {% csrf_token %}
            {% if request.user.is_authenticated %}
              <div class="card__footer">
                {% if recipe|shopping_recipe:request.user %}
                  <button class="button button_style_light-blue" name="purchases"><span
                          class="icon-check button__icon"></span>Рецепт добавлен</button>
                {% else %}
                  <button class="button button_style_blue" name="purchases" data-out><span
                          class="icon-plus button__icon"></span>Добавить в покупки</button>
                {% endif %}
                {% if recipe|is_favorite:user %}
                  <button class="button button_style_none" name="favorites" ><span class="icon-favorite icon-favorite_big icon-favorite_active"></span></button>
                  <div class="single-card__favorite-tooltip tooltip"></div>
                {% else %}
                  <button class="button button_style_none" name="favorites" data-out><span class="icon-favorite icon-favorite_big"></span></button>
                  <div class="single-card__favorite-tooltip tooltip"></div>
                {% endif %}
              </div>
            {% endif %}
        </div>
        {% endfor %}
    </div>
    {% include 'paginator.html' %}
      <script src="{% static 'js/config/config.js' %}"></script>
      <script src="{% static 'js/components/MainCards.js' %}"></script>
      <script src="{% static 'js/components/Favorites.js' %}"></script>
      <script src="{% static 'js/components/CardList.js' %}"></script>
      <script src="{% static 'js/components/Header.js' %}"></script>
      <script src="{% static 'js/components/Purchases.js' %}"></script>
      <script src="{% static 'js/api/Api.js' %}"></script>
      <script src="{% static 'indexAuth.js' %}"></script>
      <script src="{% static 'js/components/Subscribe.js' %}"></script>
{% endblock %}

templates/mysubscriptions.html
{% extends 'base.html' %}
{% block title %}Мои подписки{% endblock %}
{% block content %}
{% load static %}
{% include 'nav.html' with mysubs=True %}
{% csrf_token %}
  <link rel="stylesheet" href="{% static 'pages/myFollow.css' %}">
      <div class="main__header">
        <h1 class="main__title">Мои подписки</h1>
      </div>
    <div class="card-list">
      {% for author, recipes in fav_recipes.items %}
        <div class="card-user" data-author="{{ author.id }}">
        <div class="card-user__header">
          <h2 class="card-user__title">{{ author.get_full_name }}</h2>
        </div>
        {% for recipe in recipes %}
          <div class="card-user__body">
            <ul class="card-user__items">
              <li class="card-user__item">
                <div class="recipe">
                  <img src="{{ recipe.image.url }}" alt="{{ recipe.name }}" class="recipe__image">
                    <h3 class="recipe__title">{{ recipe.name }}</h3>
                    <p class="recipe__text"><span class="icon-time"></span>{{ recipe.prep_time }}мин.</p>
                </div>
              </li>
            </ul>
          </div>
            {% endfor %}
        <div class="card-user__footer">
          <button class="button button_style_light-blue button_size_auto"
                  name="subscribe" onclick="location.reload()">Отписаться</button>
        </div>
    </div>
    {% endfor %}
    </div>

  <script src="{% static 'js/components/MainCards.js' %}"></script>
  <script src="{% static 'js/components/MyFollow.js' %}"></script>
  <script src="{% static 'js/components/Subscribe.js' %}"></script>
  <script src="{% static 'js/config/config.js' %}"></script>
  <script src="{% static 'js/components/Header.js' %}"></script>
  <script src="{% static 'js/api/Api.js' %}"></script>
  <script src="{% static 'myFollow.js' %}"></script>
{% endblock %}

templates/nav.html
<header class="header">
  {% load static user_filters recipes_extras %}
  <nav class="nav">
    <div class="nav__container container">
      <ul class="nav__items list">
        <li class="nav__item {% if index %} nav__item_active {% endif %}"><a href="{% url 'index' %}" class="nav__link link">Рецепты</a></li>
        {% if user.is_authenticated %}
        <li class="nav__item {% if mysubs %} nav__item_active {% endif %}"><a href="{% url 'mysubscriptions' %}" class="nav__link link">Мои подписки</a></li>
        <li class="nav__item {% if recipeform %} nav__item_active {% endif %}"><a href="{% url 'newrecipe' %}" class="nav__link link">Создать рецепт</a></li>
        <li class="nav__item {% if favorites %} nav__item_active {% endif %}"><a href="{% url 'favorites' %}" class="nav__link link">Избранное</a></li>
        <li class="nav__item {% if shoplist %} nav__item_active {% endif %}"><a href="{% url 'shoplist' %}" class="nav__link link">Список покупок</a>
        <span class="badge badge_style_blue nav__badge" id="counter">{{ user|shopping_count:user.id }}</span></li>
        {% endif %}

      </ul>
      <ul class="nav__items list">
        {% if user.is_authenticated %}
          <li class="nav__item {% if pass_change %} nav__item_active {% endif %}"><a href="{% url 'password_change' %}" class="nav__link link">Изменить пароль</a></li>
          <li class="nav__item"><a href="{% url 'logout' %}" class="nav__link link">Выход</a></li>
        {% else %}
          <li class="nav__item {% if login %} nav__item_active {% endif %}"><a href="{% url 'login' %}" class="nav__link link">Войти</a></li>
          <li class="nav__item {% if signup %} nav__item_active {% endif %}"><a href="{% url 'signup' %}" class="nav__link link">Создать аккаунт</a></li>
        {% endif %}
      </ul>
    </div>
  </nav>
</header>